// Generated by https://quicktype.io

import { Vendedor } from "@shared/models/vendedor.model";
import { User } from "../../auth/interfaces/user.interface";
import { Cliente } from "../../customers/models/cliente-model";

export interface Pedido {
    id?:                    number;
    pedidoId:               number;
    orden:                  string;
    clienteId:              number;
    userId:                 number;
    vendedorId:             number;
    fecha:                  string;
    estado:                 string;
    observacion:            null;
    subtotal:               string;
    descuento:              string;
    valorGravado:           string;
    valorExcluido:          string;
    iva:                    string;
    direccionDespacho:      null;
    fechaFinaliza:          null;
    userVerifica:           null;
    cajaId:                 number;
    userFactura:            number;
    metodoPago:             string;
    terminoPago:            number;
    descripcionTerminoPago: string;
    fechaInicioPago:        null;
    fechaFinPago:           null;
    nroCheque:              null;
    movimientocajaId:       null;
    saldo:                  string;
    retefuente:             string;
    reteiva:                string;
    reteica:                string;
    codigoTipoDcto:         null;
    porcDescuento:          string;
    montoDescuento:         string;
    descripcionDescuento:   null;
    totalIpoconsumo:        string;
    tipofac:                null;
    rangofacturaId:         null;
    tarifaReteiva:          string;
    tarifaReteica:          string;
    tarifaRetefuente:       string;
    fechaFacturaManual:     null;
    fromMovil:              number;
    lat:                    number;
    lng:                    number;
    cliente:                Cliente;
    user:                   User;
    vendedor:               Vendedor;
    feHdr?:                 FeHdr;
    separationUserId?:      number;
    separationTimeStart?:   Date;
    separationTimeEnd?:     Date;
    pedidoDetalles:         PedidoDetalle[];
    separados?:             PedidoDetalle[];
    pendientes?:            PedidoDetalle[];
    userSeparation?:        User;
}


export interface PedidoDetalle {
    pedidodetalleId:           number;
    pedidoId:                  number;
    productoId:                number;
    impuestoId:                number;
    tipoPrecioId:              number;
    cantidad:                  number;
    cantidadFraccion:          number;
    precioUnidad:              number;
    precioFraccion:            number;
    descuentoUnidad:           number;
    descuentoFraccion:         number;
    ipoconsumoUnidad:          number;
    ipoconsumoFraccion:        number;
    iva:                       number;
    factorPrecio:              number;
    serial:                    null;
    costo:                     number;
    costoFraccion:             number;
    total:                     number;
    totalIpoconsumo:           number;
    totalIva:                  number;
    fechaHora:                 string;
    cantidadVerifica:          number;
    cantidadFraccionVerifica:  number;
    cantidadNoEnviada:         number;
    cantidadFraccionNoEnviada: number;
    porcDescuentoUnidad:       number;
    porcDescuentoFraccion:     number;
    codigoTipoDcto:            null;
    descripcionDescuento:      null;
    totalBaseGravableUnidad:   number;
    totalBaseGravableFraccion: number;
    lote:                      null;
    vence:                     null;
    obsequio:                  number;
    producto:                  Producto;
}

export interface Producto {
    productoId:           number;
    genericoId:           number;
    impuesto2Id:          null;
    userIdCreate:         number;
    userIdUpdate:         number;
    codigoInterno:        string;
    descripcion:          string;
    descripcionAdicional: string;
    cantidadStock:        number;
    fraccionStock:        number;
    fraccion:             number;
    stockMin:             number;
    stockMax:             number;
    unidadEmpaque:        number;
    costo:                string;
    costoFraccion:        string;
    ipoconsumo:           string;
    bloqueo:              boolean;
    facturaSinStock:      boolean;
    fechaUltimaVenta:     null;
    fechaUltimaCompra:    string;
    localizacion1:        null;
    localizacion2:        null;
    otraLocalizacion:     null;
    porcentajePromocion:  string;
    promocionFechaInicio: string;
    promocionFechaFin:    string;
    activoPromo:          boolean;
    imagen:               string;
    manejaSerie:          null;
    manejaLote:           null;
    clasificacionAbc:     null;
    valorComision:        string;
    codigoCum:            null;
    registroInvima:       null;
    fechaCreacion:        string;
    costoUltimo:          string;
    precioUnico:          boolean;
    proveedorId:          number;
    cuentaIngresoId:      number;
    cuentaInventarioId:   number;
    baseNoGravable:       boolean;
    costoChange:          boolean;
    color:                null;
    estilo:               null;
    talla:                null;
    modelo:               null;
    obsequio:             boolean;
    unidadMedidaFracId:   number;
    fil1:                 null;
    col1:                 null;
    est1:                 null;
    fil2:                 null;
    col2:                 null;
    est2:                 null;
    facturaUnimed:        boolean;
    medida:               string;
    marca:                Marca;
}

export interface Marca {
    marca_id:  number;
    nombre:    string;
}

// Generated by https://quicktype.io

export interface FeHdr {
    feHdrId:                number;
    transaccionId:          number;
    numeroFactura:          string;
    docElectronico:         string;
    cabecera:               string;
    numeroDocumento:        string;
    serie:                  string;
    folio:                  string;
    fechaEmision:           string;
    horaEmision:            string;
    timezone:               string;
    tipoFactura:            string;
    formaPago:              string;
    terminoPago:            string;
    descripcionTerminoPago: string;
    fechaInicioPago:        string;
    fechaFinPago:           string;
    metodoPago:             string;
    lugarExpedicion:        string;
    regimenFiscalEmisor:    string;
    ejercicioFiscal:        string;
    estatusDocumento:       string;
    numeroCheque:           string;
    departamento:           string;
    division:               string;
    centroCostos:           string;
    tipoOperacion:          string;
    numeroPartidas:         string;
    fechainicioPeriodo:     string;
    horainicioPeriodo:      string;
    fechafinPeriodo:        string;
    horafinPeriodo:         string;
    identificadorSucursal:  string;
    fechaSalidaBienes:      string;
    horaSalidaBienes:       string;
    identificadorPago:      string;
    caja:                   string;
    cajero:                 string;
    cajaId:                 number;
    observacion:            null;
}

